import React, { useState } from "react";
import { View, TextInput, Switch } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { NativeStackNavigationProp, NativeStackScreenProps } from "@react-navigation/native-stack";
import { RootStack } from "../navigation/types";
import { lexicon, lessons, makeReview, modalities } from "../content/course";
import { C } from "../design/theme";
import { useProgress, localDate } from "../state/Progress";
import { streak } from "../state/model";
import { ArcTitle, T, Tap, Page, Header, Button, Icon, IconButton, AudioSoon, Sheet, ProgressBar, styles as ui, IconName } from "../ui/kit";
import { AnimatedIllustration } from "../ui/AnimatedIllustration";
import { Illustration } from "../ui/Illustration";
import { Sources } from "../ui/Sources";
import { RecoverySheet } from "./Economy";
type Props<S extends keyof RootStack>=NativeStackScreenProps<RootStack,S>;
const useNav=()=>useNavigation<NativeStackNavigationProp<RootStack>>();
function Row({icon,title,subtitle,onPress,right}:{icon:IconName;title:string;subtitle?:string;onPress?:()=>void;right?:React.ReactNode}){return <Tap onPress={onPress} style={{paddingVertical:20,borderBottomWidth:1,borderColor:C.cream}}><View style={ui.row}>{icon==="sun"||icon==="shopping-bag"||icon==="award"||icon==="book-open"?<Illustration id={icon==="sun"?"racha":icon==="shopping-bag"?"backpack":icon==="award"?"trofeo":"review-book"} size={30}/>:<Icon name={icon} size={22} color={C.forest}/>}<View style={{flex:1,gap:5}}><T size={16}>{title}</T>{subtitle&&<T size={13}>{subtitle}</T>}</View>{right||<Icon name="chevron-right" size={21}/>}</View></Tap>;}
export function ReviewScreen(){
  const nav=useNav(),p=useProgress(),ids=Object.keys(p.data.review),[lives,setLives]=useState(false);
  function begin(){if(p.data.active){nav.navigate("Lesson",{recovery:false});return;}if(!p.data.lives){setLives(true);return;}const exercises=makeReview(ids.length?ids:p.data.learned);if(!exercises.length){nav.navigate("Intro",{lessonId:lessons[0].id});return;}if(p.start("personal-review",exercises,"review"))nav.navigate("Lesson",{recovery:false});}
  return <Page header={<Header/>}>
    <ArcTitle text="Vamos a recordarlo" size={31}/><T size={15} style={{textAlign:"center",marginTop:14}}>Un pequeño repaso para que{ "\n" }las palabras se queden contigo.</T><View style={{alignItems:"center",paddingVertical:29}}><AnimatedIllustration id="review-book" width={220} height={136} playing={!lives}/></View>
    <T title size={23}>{ids.length?"Tu repaso de hoy":p.data.learned.length?"Sigue practicando":"Tu primera palabra te espera"}</T><T size={14} style={{marginTop:10,marginBottom:22}}>{ids.length?`${ids.length} palabras por recordar.`:p.data.learned.length?"No tienes palabras pendientes. Puedes volver a practicar las que conoces.":"Aquí volverás a encontrar las palabras que necesitan un poco más de práctica."}</T>
    <Button disabled={p.busy} text={p.data.active?"Retomar misión en pausa":ids.length||p.data.learned.length?"Empezar repaso":"Ir a mi primera misión"} onPress={begin}/>
    {ids.map(id=><Row key={id} icon="rotate-ccw" title={lexicon[id].form} subtitle={lexicon[id].meaningEs} onPress={()=>nav.navigate("Word",{id})}/>)}
    <RecoverySheet visible={lives} onClose={()=>setLives(false)}/>
  </Page>;
}
export function CollectionScreen(){
  const nav=useNav(),p=useProgress(),[query,setQuery]=useState(""),[filter,setFilter]=useState("Aprendidas");
  const normalize=(text:string)=>text.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
  const list=Object.values(lexicon).filter(w=>(filter==="Todas"||(filter==="Aprendidas"?p.data.learned:p.data.bookmarks).includes(w.id))&&normalize(w.form+" "+w.meaningEs).includes(normalize(query)));
  return <Page header={<Header/>}>
    <ArcTitle text="Tus palabras" size={34}/><T size={14} style={{textAlign:"center",marginTop:12,marginBottom:25}}>Un pequeño mundo que crece contigo.</T>
    <View style={{...ui.row,borderWidth:1,borderColor:C.caramel,borderRadius:13,paddingHorizontal:14,backgroundColor:C.surface}}><Icon name="search" size={20}/><TextInput accessibilityLabel="Buscar una palabra" placeholder="Buscar una palabra" placeholderTextColor={C.cocoa+"99"} value={query} onChangeText={setQuery} style={[ui.field,{flex:1,borderWidth:0,paddingHorizontal:0}]} autoCapitalize="none" autoCorrect={false}/>{!!query&&<IconButton name="x" label="Borrar búsqueda" onPress={()=>setQuery("")}/>}</View>
    <View style={{flexDirection:"row",marginTop:15,marginBottom:17,borderBottomWidth:1,borderColor:C.cream}}>{["Aprendidas","Todas","Guardadas"].map(f=><Tap key={f} role="tab" selected={filter===f} onPress={()=>setFilter(f)} style={{flex:1,alignItems:"center",minHeight:49,borderBottomWidth:filter===f?3:0,borderColor:C.forest}}><T size={14} color={filter===f?C.forest:C.cocoa}>{f}</T></Tap>)}</View>
    <T size={12}>{list.length} {list.length===1?"palabra":"palabras"}</T>
    {list.length?list.map(w=><Tap key={w.id} label={`Ver ${w.form}, ${w.meaningEs}`} onPress={()=>nav.navigate("Word",{id:w.id})} style={{paddingVertical:17,borderBottomWidth:1,borderColor:C.cream}}><View style={ui.row}><Illustration id={w.illustration} width={80} height={60}/><View style={{flex:1,gap:5}}><T title size={24}>{w.form}</T><T size={14}>{w.meaningEs}</T></View><Icon name={p.data.bookmarks.includes(w.id)?"bookmark":"chevron-right"} size={21} color={C.forest}/></View></Tap>):<View style={{alignItems:"center",paddingVertical:35,gap:20}}><AnimatedIllustration id="empty-collection" width={210} height={135}/><T size={18} style={{textAlign:"center"}}>{query?"No encontramos esa palabra":filter==="Guardadas"?"Aún no hay palabras guardadas":"Aquí empieza tu colección"}</T><T size={14} style={{textAlign:"center"}}>{query?"Prueba con su significado en español.":filter==="Guardadas"?"Abre una palabra y toca el marcador.":"Completa una misión para ver lo que aprendiste."}</T><Button secondary text="Ver todas las palabras" onPress={()=>{setFilter("Todas");setQuery("");}}/></View>}
  </Page>;
}
export function WordScreen({navigation,route}:Props<"Word">){const p=useProgress(),w=lexicon[route.params.id];if(!w)return <Page><T>Palabra no disponible.</T></Page>;return <Page header={<Header back={()=>navigation.goBack()} right={<IconButton name="bookmark" label={p.data.bookmarks.includes(w.id)?"Quitar de guardadas":"Guardar palabra"} onPress={()=>p.bookmark(w.id)}/>}/>} footer={<Button secondary text={p.data.review[w.id]?"Añadida a tu repaso":"Añadir al repaso"} disabled={!!p.data.review[w.id]} onPress={()=>p.addReview(w.id)}/>}>
  <View style={{alignItems:"center",gap:17,paddingTop:27}}>{w.id==="p'anqa"?<AnimatedIllustration id="p'anqa" width={290} height={190}/>:<Illustration id={w.illustration} width={290} height={190}/>}<T title size={44}>{w.form}</T><T size={23} style={{textAlign:"center"}}>{w.meaningEs}</T><AudioSoon/>{p.data.bookmarks.includes(w.id)&&<T size={13} color={C.forest}>Guardada en tu colección</T>}</View>
  {w.variants.map(v=><View key={v.form} style={{marginTop:23,gap:7}}><T size={17}>También: {v.form}</T><T size={13}>Variante aceptada para esta entrada.</T></View>)}<Sources ids={[w.id]}/>
</Page>;}
export function ProfileScreen(){const nav=useNav(),p=useProgress(),completed=Object.keys(p.data.completed).length,daily=(p.data.missionDays[localDate()]||[]).length;return <Page header={<Header right={<IconButton name="settings" label="Abrir ajustes" onPress={()=>nav.navigate("Settings")}/>}/>}>
  <View style={{alignItems:"center",gap:13,marginVertical:19}}><View style={{height:87,width:87,borderRadius:44,alignItems:"center",justifyContent:"center",backgroundColor:C.cream}}><T title size={41}>{Array.from(p.data.name)[0]?.toUpperCase()}</T></View><T title size={29} style={{textAlign:"center"}}>{p.data.name}</T><T size={14}>Aprendiendo quechua</T><Tap onPress={()=>nav.navigate("EditProfile")}><T size={13} color={C.forest} style={{textDecorationLine:"underline"}}>Editar mi nombre</T></Tap></View>
  <View style={{flexDirection:"row",paddingVertical:18,borderTopWidth:1,borderBottomWidth:1,borderColor:C.cream}}>{[{n:p.data.learned.length,label:p.data.learned.length===1?"palabra":"palabras"},{n:completed,label:completed===1?"misión":"misiones"},{n:streak(p.data),label:streak(p.data)===1?"día de racha":"días de racha"}].map(item=><View key={item.label} style={{flex:1,alignItems:"center",gap:6}}><T title size={31} color={C.forest}>{item.n}</T><T size={12}>{item.label}</T></View>)}</View>
  <View style={{marginVertical:22,gap:11}}><View style={{...ui.row,justifyContent:"space-between"}}><T size={15}>Tu objetivo de hoy</T><T size={13}>{Math.min(daily,p.data.goal)}/{p.data.goal}</T></View><ProgressBar value={Math.min(1,daily/p.data.goal)} label="Objetivo de hoy"/></View>
  <Row icon="sun" title="Mi constancia" subtitle="Calendario de misiones" onPress={()=>nav.navigate("Streak")}/><Row icon="shopping-bag" title="Mi mochila" subtitle={`${p.data.seeds} semillas`} onPress={()=>nav.navigate("Backpack")}/><Row icon="award" title="Mis pequeños logros" onPress={()=>nav.navigate("About")}/><Row icon="settings" title="Ajustes" onPress={()=>nav.navigate("Settings")}/><T size={12} style={{textAlign:"center",marginTop:24}}>Invitado · progreso en este dispositivo</T>
</Page>;}
export function EditProfile({navigation}:Props<"EditProfile">){const p=useProgress(),[name,setName]=useState(p.data.name);return <Page header={<Header back={()=>navigation.goBack()}/>} footer={<Button text="Guardar nombre" disabled={!name.trim()||p.busy} onPress={()=>{p.update(d=>({...d,name:name.trim().slice(0,36)}));navigation.goBack();}}/>}>
  <ArcTitle text="Así te llamamos" size={33}/><View style={{alignItems:"center",paddingVertical:32}}><View style={{width:90,height:90,borderRadius:45,backgroundColor:C.cream,alignItems:"center",justifyContent:"center"}}><T title size={40}>{Array.from(name)[0]?.toUpperCase()||"M"}</T></View></View><T style={{marginBottom:10}}>Nombre</T><TextInput accessibilityLabel="Nombre" value={name} onChangeText={setName} maxLength={36} style={ui.field} autoComplete="off" placeholder="Tu nombre" placeholderTextColor={C.cocoa+"99"}/><T size={13} style={{marginTop:17}}>Tu nombre se queda en este dispositivo.</T>
</Page>;}
export function SettingsScreen({navigation}:Props<"Settings">){const p=useProgress(),[resetOpen,setResetOpen]=useState(false);return <Page header={<Header back={()=>navigation.goBack()}/>}>
  <ArcTitle text="A tu manera" size={34}/>
  {[{key:"vibration",title:"Vibración",subtitle:"Una respuesta breve al equivocarte",icon:"smartphone"},{key:"reduceMotion",title:"Reducir movimiento",subtitle:"También respeta el ajuste del teléfono",icon:"wind"}].map(item=><View key={item.key} style={{paddingVertical:21,borderBottomWidth:1,borderColor:C.cream,...ui.row}}><Icon name={item.icon as IconName} color={C.forest}/><View style={{flex:1,gap:6}}><T>{item.title}</T><T size={12}>{item.subtitle}</T></View><Switch accessibilityLabel={item.title} value={p.data[item.key as "vibration"|"reduceMotion"]} onValueChange={v=>p.update(d=>({...d,[item.key]:v}))} trackColor={{false:C.caramel,true:C.forest}} thumbColor={C.surface}/></View>)}
  <Row icon="sun" title="Objetivo diario" subtitle={`${p.data.goal} ${p.data.goal===1?"misión":"misiones"}`} onPress={()=>navigation.navigate("Goal",{editing:true})}/><Row icon="globe" title="Idioma" subtitle="Quechua · Aymara próximamente" onPress={()=>navigation.navigate("Language")}/><View style={{paddingVertical:20,borderBottomWidth:1,borderColor:C.cream}}><AudioSoon/></View><Row icon="book-open" title="Proyecto y fuentes" onPress={()=>navigation.navigate("About")}/><Row icon="shield" title="Tus datos" subtitle="Nombre, preferencias y progreso local" onPress={()=>navigation.navigate("About")}/><Tap onPress={()=>setResetOpen(true)} style={{paddingVertical:22}}><T size={14} color={C.terracotta}>Borrar mi progreso</T></Tap>
  <Sheet visible={resetOpen} title="¿Empezar desde cero?" onClose={()=>setResetOpen(false)}><T>Se borrarán las misiones, palabras guardadas, repasos y preferencias de este dispositivo. No se puede deshacer.</T><Button text="Conservar mi progreso" onPress={()=>setResetOpen(false)}/><Button secondary disabled={p.busy} text="Borrar y empezar de nuevo" onPress={()=>{setResetOpen(false);p.reset();navigation.reset({index:0,routes:[{name:"Welcome"}]});}}/></Sheet>
</Page>;}
export function AboutScreen({navigation}:Props<"About">){const p=useProgress();return <Page header={<Header back={()=>navigation.goBack()}/>}><ArcTitle text="Detrás de Muni"/><T style={{marginTop:20}}>Una palabra, una práctica y un camino para seguir aprendiendo.</T><View style={{alignItems:"center",paddingTop:28}}><Illustration id="trofeo" width={100} height={104}/></View><T title size={23} style={{marginTop:16}}>Tus logros</T>{[{title:"Primer paso",done:Object.keys(p.data.completed).length>0,description:"Completa tu primera misión"},{title:"El valle recorrido",done:lessons.filter(l=>l.unit===1).every(l=>p.data.completed[l.id]),description:"Completa las cuatro misiones del valle"},{title:"Diez palabras",done:p.data.learned.length>=10,description:"Aprende diez palabras"}].map(item=><View key={item.title} style={{paddingVertical:20,...ui.row}}><Icon name={item.done?"check-circle":"lock"} color={C.forest}/><View style={{flex:1,gap:6}}><T>{item.title}</T><T size={13}>{item.done?"Conseguido":item.description}</T></View></View>)}<T title size={23} style={{marginTop:22}}>Un curso que cuidamos</T><T size={14} style={{marginTop:15}}>Las palabras provienen del Diccionario de la Nación Quechua del CENAQ. Las fichas conservan sus páginas, formas y variantes. El contraste documental no equivale a revisión de un hablante; esa revisión sigue pendiente.</T><Sources ids={["wasi","inti","yaku"]}/><T title size={23} style={{marginTop:25}}>Formas de practicar</T>{modalities.map(m=><View key={m.id} style={{paddingVertical:13,...ui.row}}><Icon name={m.status==="enabled"?"check":"clock"} size={18} color={C.forest}/><T size={14} style={{flex:1}}>{m.title}{m.status==="pending"?" · Próximamente":""}</T></View>)}<T title size={23} style={{marginTop:24}}>Tu progreso vive aquí</T><T size={14} style={{marginTop:14}}>El modo invitado guarda tu nombre, preferencias y avance en este dispositivo. No se sincroniza. Borrar los datos o desinstalar la app puede eliminarlos. Muni no guarda contraseñas ni usa el micrófono.</T><T size={12} style={{marginTop:26}}>Muni · 1.0.0</T></Page>;}
