import React, { useState } from "react";
import { View, TextInput, useWindowDimensions } from "react-native";
import { NativeStackScreenProps } from "@react-navigation/native-stack";
import { RootStack } from "../navigation/types";
import { C } from "../design/theme";
import { useProgress } from "../state/Progress";
import { ArcTitle, Page, Header, Logo, T, Button, Character, Tap, Icon, styles as ui } from "../ui/kit";
import { AnimatedIllustration } from "../ui/AnimatedIllustration";
import { Illustration, Landscape } from "../ui/Illustration";
type Props<S extends keyof RootStack>=NativeStackScreenProps<RootStack,S>;
export function Welcome({navigation}:Props<"Welcome">){const {width,height}=useWindowDimensions();const sceneWidth=Math.min(width,600);return <Page header={<View style={{height:73,alignItems:"center",justifyContent:"center"}}><Logo width={103}/></View>} footer={<><Button text="Continuar como invitado" onPress={()=>navigation.navigate("Language")}/><Tap onPress={()=>navigation.navigate("Account",{mode:"login"})}><T size={14} style={{textAlign:"center"}}>Ya tengo una cuenta</T></Tap></>}>
  <View style={{flex:1,alignItems:"center",paddingTop:12}}><ArcTitle text="Hola, soy Muni" size={35}/><T size={17} style={{textAlign:"center",marginTop:15,maxWidth:290}}>Aprendamos quechua,{"\n"}una palabra a la vez.</T><View style={{width:"100%",height:Math.min(310,height*.37),marginTop:18,marginBottom:16,alignItems:"center"}}><View style={{position:"absolute",bottom:0,width:sceneWidth,alignItems:"center"}}><Landscape width={sceneWidth}/></View><View style={{position:"absolute",bottom:5}}><AnimatedIllustration id="muni-welcome" height={Math.min(267,height*.315)} fallback={<Character height={Math.min(267,height*.315)}/>}/></View></View><T size={13} style={{textAlign:"center"}}>Tu primer camino empieza en Bolivia.</T></View>
</Page>;}
export function Language({navigation}:Props<"Language">){const p=useProgress();return <Page header={<Header back={()=>navigation.goBack()}/>} footer={<Button text={p.data.onboarded?"Volver a ajustes":"Continuar"} onPress={()=>p.data.onboarded?navigation.goBack():navigation.navigate("Goal")}/> }>
  <ArcTitle text="Elige tu idioma" size={34}/><T style={{textAlign:"center",marginTop:18,marginBottom:36}}>Un idioma, muchas formas{ "\n" }de ver el mundo.</T>
  {[{name:"Quechua",region:"Bolivia",ready:true},{name:"Aymara",region:"Próximamente",ready:false}].map(l=><View key={l.name} accessible accessibilityRole="radio" accessibilityLabel={`${l.name}, ${l.region}`} accessibilityState={{selected:l.ready,checked:l.ready,disabled:!l.ready}} style={{borderWidth:l.ready?2:1,borderColor:l.ready?C.forest:C.cream,borderRadius:18,backgroundColor:C.surface,padding:16,marginBottom:18,...ui.row}}><Illustration id={l.name} width={105} height={88}/><View style={{flex:1,gap:7}}><T title size={26}>{l.name}</T><T size={14}>{l.region}</T></View><Icon name={l.ready?"check-circle":"lock"} color={l.ready?C.forest:C.cocoa} size={23}/></View>)}
</Page>;}
export function Goal({navigation,route}:Props<"Goal">){const p=useProgress(),[goal,setGoal]=useState(p.data.goal),editing=route.params?.editing;return <Page header={<Header back={()=>navigation.goBack()}/>} footer={<Button text={editing?"Guardar objetivo":"Empezar mi camino"} disabled={p.busy} onPress={()=>{p.update(d=>({...d,goal,onboarded:true}));editing?navigation.goBack():navigation.reset({index:0,routes:[{name:"Main"}]});}}/>}>
  <View style={{alignItems:"center",paddingTop:8}}><AnimatedIllustration id="brote" width={83} height={62}/></View><ArcTitle text="Tu ritmo" size={35}/><T style={{textAlign:"center",marginTop:10,marginBottom:15}}>Elige un ritmo que vaya contigo.</T>
  {[1,2,3].map(n=><Tap key={n} role="radio" selected={goal===n} label={`${n} ${n===1?"misión":"misiones"} al día`} onPress={()=>setGoal(n)} style={{paddingVertical:20,borderBottomWidth:1,borderColor:C.cream}}><View style={ui.row}><View style={{flex:1,gap:7}}><T size={20}>{n} {n===1?"misión":"misiones"}</T><T size={14}>{n===1?"Un momento para ti":n===2?"Un paso más":"Tiempo para explorar"}</T></View><Icon name={goal===n?"check-circle":"circle"} color={C.forest} size={27}/></View></Tap>)}<T size={13} style={{textAlign:"center",marginTop:22}}>Puedes cambiarlo después. Sin presión.</T>
</Page>;}
export function Account({navigation,route}:Props<"Account">){const mode=route.params.mode,register=mode==="register",recovery=mode==="recovery";const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState("");return <Page header={<Header back={()=>navigation.goBack()} right={<Logo width={82}/>}/>} footer={<Button text="Continuar como invitado" onPress={()=>navigation.navigate("Language")}/>}>
  <ArcTitle text={recovery?"Volvamos a empezar":register?"Tu aventura empieza":"Qué bueno verte"} size={32}/><T size={14} style={{textAlign:"center",marginTop:16,marginBottom:25}}>Las cuentas estarán disponibles más adelante. Por ahora, aprende como invitado.</T>
  {recovery&&<View style={{height:106,alignItems:"center",justifyContent:"center",marginBottom:18}}><Illustration id="sobre" width={120} height={88}/><View style={{position:"absolute",left:"61%",top:47,transform:[{rotate:"18deg"}]}}><Illustration id="llave" width={40} height={64}/></View></View>}
  {register&&<View style={{gap:9,marginBottom:18}}><T>Nombre</T><TextInput accessibilityLabel="Nombre" placeholder="Tu nombre" placeholderTextColor={C.cocoa+"99"} value={name} onChangeText={setName} style={ui.field}/></View>}
  <View style={{gap:9,marginBottom:18}}><T>Correo electrónico</T><TextInput accessibilityLabel="Correo electrónico" placeholder="Tu correo" placeholderTextColor={C.cocoa+"99"} keyboardType="email-address" autoCapitalize="none" autoCorrect={false} autoComplete="off" value={email} onChangeText={setEmail} style={ui.field}/></View>
  {!recovery&&<View style={{gap:9,marginBottom:18}}><T>Contraseña</T><TextInput accessibilityLabel="Contraseña" placeholder="Tu contraseña" placeholderTextColor={C.cocoa+"99"} secureTextEntry autoComplete="off" autoCapitalize="none" value={password} onChangeText={setPassword} style={ui.field}/></View>}
  <Button text={recovery?"Recuperación próximamente":register?"Registro próximamente":"Acceso próximamente"} disabled/>
  {recovery?<T size={13} style={{marginTop:17}}>Todavía no enviamos correos de recuperación.</T>:<><Tap onPress={()=>navigation.push("Account",{mode:register?"login":"register"})}><T size={14} style={ui.link}>{register?"Ya tengo una cuenta":"Quiero crear una cuenta"}</T></Tap>{!register&&<Tap onPress={()=>navigation.push("Account",{mode:"recovery"})}><T size={14} style={{textAlign:"center"}}>Olvidé mi contraseña</T></Tap>}</>}
</Page>;}
