import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
// Original Figma bytes stay untouched. Only the exported editor canvas is removed.
const assets = [
  ["brand/logo-cocoa", "8:79"],
  ["brand/logo-cream", "8:49"],
  ["brand/icon", "8:34"],
  ["character/muni-idle", "1:2"],
];
fs.mkdirSync("src/design", { recursive: true });
fs.mkdirSync("assets/derived", { recursive: true });
const module = {};
const manifest = JSON.parse(fs.readFileSync("assets/manifest.json", "utf8"));
for (const [id, nodeId] of assets) {
  const original = fs.readFileSync(`assets/${id}.svg`, "utf8");
  if (/<image\b/i.test(original))
    throw new Error(`${id} contains a raster image`);
  const name = path.basename(id);
  const xml = original
    .replace(/<rect width="[^"]+" height="[^"]+" fill="#1E1E1E"\s*\/>/i, "")
    .replace(/id="([^"]+)"/g, (_, value) => `id="${name}-${value}"`)
    .replace(/url\(#([^)]*)\)/g, (_, value) => `url(#${name}-${value})`);
  fs.writeFileSync(`assets/derived/${name}.svg`, xml);
  module[name] = xml;
  const entry = {
    id,
    kind: id.startsWith("brand") ? "brand-vector" : "illustration-vector",
    status: "downloaded",
    figmaNodeId: nodeId,
    localPath: `assets/${id}.svg`,
    derivedPath: `assets/derived/${name}.svg`,
    sha256: crypto.createHash("sha256").update(original).digest("hex"),
    downloadedAt: "2026-09-08",
    transformation:
      "Removed only outer #1E1E1E editor rectangle; prefixed SVG IDs to avoid clip collisions. Paths and original colors retained.",
    rasterEmbedded: false,
  };
  const index = manifest.assets.findIndex((x) => x.id === id);
  if (index >= 0) manifest.assets[index] = entry;
  else manifest.assets.push(entry);
}
// Update only the four brand entries. Preserve component packages, supplied-file
// provenance and the current connection status in the existing manifest.
fs.writeFileSync(
  "assets/manifest.json",
  JSON.stringify(manifest, null, 2) + "\n",
);
fs.writeFileSync(
  "src/design/figma-assets.ts",
  "// Generated by scripts/prepare-assets.mjs from local original SVGs.\nexport const figmaAssets = " +
    JSON.stringify(module, null, 2) +
    " as const;\n",
);
console.log("Prepared four local vector assets; no embedded raster images.");
